package com.leinb1dr.pubg.afteractionreport.core

data class SeasonStats(
    override val assists: Int,
    override val boosts: Int,
    override val DBNOs: Int,
    val dailyKills: Int,
    val dailyWins: Int,
    override val damageDealt: Double,
    val days: Int,
    override val headshotKills: Int,
    override val heals: Int,
    val killPoints: Double,
    override val kills: Int,
    override val longestKill: Double,
    val longestTimeSurvived: Double,
    val losses: Int,
    val maxKillStreaks: Int,
    val mostSurvivalTime: Int,
    val rankPoints: Double,
    val rankPointsTitle: String,
    override val revives: Int,
    override val rideDistance: Double,
    override val roadKills: Int,
    val roundMostKills: Int,
    val roundsPlayed: Int,
    val suicides: Int,
    override val swimDistance: Double,
    override val teamKills: Int,
    override val timeSurvived: Int,
    val top10s: Int,
    override val vehicleDestroys: Int,
    override val walkDistance: Double,
    override val weaponsAcquired: Int,
    val weeklyKills: Int,
    val weeklyWins: Int,
    val winPoints: Double,
    val wins: Int
): AbstractStats(){
    companion object Default{
        fun empty() = SeasonStats(
            0,
            0,
            0,
            0,
            0,
            0.0,
            0,
            0,
            0,
            0.0,
            0,
            0.0,
            0.0,
            0,
            0,
            0,
            0.0,
            "",
            0,
            0.0,
            0,
            0,
            1,
            0,
            0.0,
            0,
            0,
            0,
            0,
            0.0,
            0,
            0,
            0,
            0.0,
            0
        )
    }
}
