spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:27017/?authMechanism=SCRAM-SHA-1
      database: ${MONGO_DATABASE}

management:
  metrics:
    export:
      stackdriver:
        project-id: leinb1dr-test-application-1
        enabled: false
        steps: "10S"
        batch-size: 100
    tags:
      application: after-action-report
      env: poc