spring:
  application:
    name: after-action-report
  main:
    allow-bean-definition-overriding: true
  jackson:
    deserialization:
      accept_single_value_as_array: true
  data:
    mongodb:
      database: ${MONGO_DATABASE}
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include:
          - metrics
          - prometheus
          - health
          - liveness