apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    app: {{ include "fullname" . }}
spec:
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.image.port}}
  selector:
    app: {{ include "fullname" . }}