apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aar.fullname" . }}
  labels:
    app: {{ include "aar.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "aar.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "aar.fullname" . }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: {{ include "aar.fullname" . }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: Always
          ports:
          - name: aar
            containerPort: {{ .Values.image.port }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 10Mi
              memory: 512Mi
            requests:
              cpu: 250m
              ephemeral-storage: 10Mi
              memory: 512Mi
          volumeMounts:
            - name: serviceaccount-secret
              mountPath: /var/secrets/google
          env:
#            - name: IO_MICROMETER_SHADED_IO_NETTY_TRANSPORT_NONATIVE
#              value: "true"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SPRING_SECURITY_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "aar.fullname" . }}-secret
                  key: managementUser
            - name: SPRING_SECURITY_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "aar.fullname" . }}-secret
                  key: managementPassword
            - name: APP_PUBGTOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "aar.fullname" . }}-secret
                  key: pubgToken
            - name: APP_DISCORDWEBHOOK
              valueFrom:
                secretKeyRef:
                  name: {{ include "aar.fullname" . }}-secret
                  key: discordWebHook
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "aar.fullname" . }}-secret
                  key: dbUsername
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "aar.fullname" . }}-secret
                  key: dbPassword
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "aar.fullname" . }}-config
                  key: mongoHost
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "aar.fullname" . }}-config
                  key: databaseName
      volumes:
        - name: serviceaccount-secret
          secret:
            secretName: {{ include "aar.fullname" . }}-serviceaccount-secret