package com.leinb1dr.pub.afteractionreport.core

data class ParticipantStats(
    override val assists: Int,
    override val damageDealt: Double,
    override val DBNOs: Int,
    val deathType: String = "none",
    override val boosts: Int,
    override val headshotKills: Int,
    override val heals: Int,
    val killPlace: Int,
    override val kills: Int,
    val killStreaks: Int,
    override val longestKill: Double,
    val name: String = "#PlayerUnknown",
    val playerId: String = "#PlayerUnknown",
    override val revives: Int,
    override val rideDistance: Double,
    override val roadKills: Int,
    override val swimDistance: Double,
    override val teamKills: Int,
    override val timeSurvived: Int,
    override val vehicleDestroys: Int,
    override val walkDistance: Double,
    override val weaponsAcquired: Int,
    val winPlace: Int,
) : AbstractStats()
