apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-config
data:
  MONGO_HOST: {{ .Release.Name }}-{{ .Values.config.mongoHost }}
  MONGO_DATABASE: {{ .Values.config.database }}