apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-service
spec:
  selector:
    app.kubernetes.io/name: {{ include "fullname" . }}
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetPort: {{.Values.image.port}}