name: Build Gradle project

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 14
        uses: actions/setup-java@v3
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        env: # Or as an environment variable
          APP_PUBGTOKEN: ${{ secrets.APP_PUBGTOKEN }}
          APP_DISCORDWEBHOOK: ${{ secrets.APP_PUBGTOKEN }}
        with:
          arguments: build
